language: android
android:
  components:
    - build-tools-26.0.2
    - android-26
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
notifications:
  slack: quantiteam:svjsHPVDuNZTLdB8Sl5IT7jK